#!/usr/bin/env python3
"""Apply migration 029: Classification Claims schema foundation (Class D DDL).

Standalone script — deliberately NOT wired into db.connection._run_migrations()
or init_db(). The schema stays inert in every environment until an operator
explicitly runs --apply (or --rollback) here (Codex decision).

Six new tables, purely additive. No existing table (companies included) is
touched. No data is written, backfilled, or seeded by this script.

CLI artifact-path contract: --dry-run [PATH] writes to PATH (default if
omitted). --apply reads from the SAME path, given as --artifact-path PATH
(default if omitted) — the two flags share one fixed default and one
explicit override, so a dry-run written to a custom path is never silently
missed by --apply.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import config.env  # noqa: F401

from db.classification_claims_ddl import (
    classification_claims_ddl_digest,
    classification_claims_migration_statements,
    is_valid_ddl_digest,
)
from db.classification_claims_migration import (
    ApplyReadinessStatus,
    ClassificationClaimsRollbackBlockedError,
    ClassificationClaimsSchemaCorruptError,
    apply_classification_claims_migration,
    apply_classification_claims_rollback,
    classification_claims_apply_readiness,
    classification_claims_before_stats,
)
from db.connection import get_engine, get_session
from db.db_safety import (
    add_production_safety_args,
    guard_destructive_db_from_args,
    guard_readonly_db_from_args,
)
from db.merge_dry_run_provenance import get_git_commit_sha

_SCRIPT = Path(__file__).name
DEFAULT_DRY_RUN_ARTIFACT = (
    ROOT / "exports" / "classification_claims_migration_dryrun_class_d.json"
)


def _build_dry_run_report(session, *, artifact_path: Path) -> dict:
    before = classification_claims_before_stats(session)
    statements = classification_claims_migration_statements()
    return {
        "operation": "classification_claims_schema_migration",
        "class": "D",
        "dry_run": True,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "git_commit_sha": get_git_commit_sha(),
        "ddl_digest": classification_claims_ddl_digest(),
        "artifact_path": str(artifact_path),
        "migration": "029_classification_claims",
        "production_before": before,
        "planned_mutations": {
            "destructive_delete": False,
            "ddl_only": True,
            "statements_planned": len(statements),
            "already_applied": not before.get("migration_pending", True),
        },
        "ddl_plan": {"statements": statements},
        "apply_command_preview": (
            "python scripts/run_classification_claims_migration.py --apply --allow-production"
        ),
        "not_wired_to": ["db.connection._run_migrations()", "db.connection.init_db()"],
    }


def _verify_dry_run_artifact(*, session, report_path: Path) -> None:
    """Refuse apply when the dry-run artifact is missing, malformed, or
    stale vs. the current commit, the current DDL, or the current
    schema-existence state.

    A missing, non-JSON, or missing/malformed ddl_digest field is treated
    identically to a mismatched digest — all block apply as a stale
    artifact. This is deliberately strict: an artifact generated by an
    older version of this script (before ddl_digest existed) is stale by
    definition, not merely "unverifiable."
    """
    if not report_path.is_file():
        print(
            f"[db_safety] dry-run is stale — regenerate before apply.\n"
            f"  Missing artifact: {report_path}",
            file=sys.stderr,
        )
        raise SystemExit(1)

    try:
        payload = json.loads(report_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        print(
            f"[db_safety] dry-run is stale — regenerate before apply.\n"
            f"  Invalid JSON in {report_path}: {exc}",
            file=sys.stderr,
        )
        raise SystemExit(1)

    expected_sha = get_git_commit_sha()
    recorded_sha = str(payload.get("git_commit_sha", ""))
    if recorded_sha != expected_sha:
        print(
            "[db_safety] dry-run is stale — regenerate before apply.\n"
            f"  git commit mismatch: artifact={recorded_sha} current={expected_sha}",
            file=sys.stderr,
        )
        raise SystemExit(1)

    recorded_digest = payload.get("ddl_digest")
    expected_digest = classification_claims_ddl_digest()
    if not is_valid_ddl_digest(recorded_digest):
        print(
            "[db_safety] dry-run is stale — regenerate before apply.\n"
            f"  artifact ddl_digest is missing or malformed: {recorded_digest!r}",
            file=sys.stderr,
        )
        raise SystemExit(1)
    if recorded_digest != expected_digest:
        print(
            "[db_safety] dry-run is stale — regenerate before apply.\n"
            "  DDL changed since this dry-run was generated "
            "(029_classification_claims.sql does not match the artifact).\n"
            f"  artifact ddl_digest={recorded_digest} current ddl_digest={expected_digest}",
            file=sys.stderr,
        )
        raise SystemExit(1)

    current_before = classification_claims_before_stats(session)
    recorded_before = payload.get("production_before")
    if recorded_before != current_before:
        print(
            "[db_safety] dry-run is stale — regenerate before apply.\n"
            "  schema state changed since dry-run was generated.\n"
            f"  artifact production_before={recorded_before}\n"
            f"  current production_before={current_before}",
            file=sys.stderr,
        )
        raise SystemExit(1)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    add_production_safety_args(parser)
    parser.add_argument(
        "--dry-run",
        nargs="?",
        const=str(DEFAULT_DRY_RUN_ARTIFACT),
        metavar="ARTIFACT",
        help="Write dry-run artifact JSON (default path if flag given without value).",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Execute migration 029 DDL (requires a fresh dry-run artifact).",
    )
    parser.add_argument(
        "--artifact-path",
        metavar="PATH",
        default=None,
        help=(
            "Dry-run artifact path for --apply to read (default: "
            f"{DEFAULT_DRY_RUN_ARTIFACT}). Must match the path used with --dry-run."
        ),
    )
    parser.add_argument(
        "--rollback",
        action="store_true",
        help="Drop all six classification-claims tables (refuses if any table is non-empty).",
    )
    args = parser.parse_args()

    modes_selected = sum([args.apply, args.rollback, args.dry_run is not None])
    if modes_selected > 1:
        parser.error("Use only one of --dry-run, --apply, --rollback.")
    if args.artifact_path is not None and not args.apply:
        parser.error("--artifact-path is only valid together with --apply.")

    if args.apply:
        apply_artifact_path = (
            Path(args.artifact_path)
            if args.artifact_path is not None
            else DEFAULT_DRY_RUN_ARTIFACT
        )
        guard_destructive_db_from_args(
            args,
            script_name=_SCRIPT,
            operation="classification_claims schema migration (029)",
        )
        session = get_session()
        try:
            _verify_dry_run_artifact(session=session, report_path=apply_artifact_path)

            readiness = classification_claims_apply_readiness(session)
            if readiness.status is ApplyReadinessStatus.FULLY_APPLIED:
                print("[Migration 029] Already applied — nothing to do.")
                return
            if readiness.status is ApplyReadinessStatus.CORRUPT:
                raise ClassificationClaimsSchemaCorruptError(
                    "Refusing to apply: the classification-claims schema exists but does not "
                    "fully match the expected contract (029_classification_claims.sql). "
                    "This script never repairs a schema silently.\n"
                    "  Violations:\n"
                    + "\n".join(f"    - {v}" for v in readiness.violations)
                    + "\n  Next step: run scripts/run_classification_claims_schema_audit.py "
                    "for a full report, then either fix forward with a new migration or, if "
                    "every table is confirmed empty, roll back (--rollback) and reapply."
                )
            # NOT_APPLIED: proceed.
        finally:
            session.close()

        engine = get_engine()
        result = apply_classification_claims_migration(engine)
        print("[Migration 029] Apply complete:")
        for key, value in result.items():
            print(f"  {key}: {value}")
        return

    if args.rollback:
        guard_destructive_db_from_args(
            args,
            script_name=_SCRIPT,
            operation="classification_claims schema rollback (029)",
        )
        engine = get_engine()
        try:
            result = apply_classification_claims_rollback(engine)
        except ClassificationClaimsRollbackBlockedError as exc:
            print(f"[Migration 029] Rollback refused: {exc}", file=sys.stderr)
            raise SystemExit(1) from exc
        print("[Migration 029] Rollback complete:")
        for key, value in result.items():
            print(f"  {key}: {value}")
        return

    artifact_path = (
        Path(args.dry_run) if args.dry_run is not None else DEFAULT_DRY_RUN_ARTIFACT
    )
    guard_readonly_db_from_args(args, script_name=_SCRIPT)
    session = get_session()
    try:
        report = _build_dry_run_report(session, artifact_path=artifact_path)
    finally:
        session.close()

    artifact_path.parent.mkdir(parents=True, exist_ok=True)
    artifact_path.write_text(
        json.dumps(report, indent=2, default=str), encoding="utf-8"
    )
    print(json.dumps(report, indent=2, default=str))
    print(f"\nWrote {artifact_path}")


if __name__ == "__main__":
    main()
